/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "surface-container-high": "#e3edf2",
          "surface-tint": "#13a8d8",
          "on-tertiary-container": "#ff8a3d",
          "on-primary": "#ffffff",
          "on-secondary-fixed-variant": "#7a3200",
          "tertiary-fixed-dim": "#ffbd91",
          "surface": "#f7fbfd",
          "inverse-primary": "#8ee0f4",
          "inverse-on-surface": "#eef6f9",
          "error": "#ba1a1a",
          "primary-fixed": "#d8f4fb",
          "outline": "#737781",
          "on-secondary": "#ffffff",
          "secondary": "#d95f00",
          "on-background": "#171c1f",
          "on-tertiary-fixed-variant": "#813500",
          "on-error-container": "#93000a",
          "primary-container": "#007db3",
          "on-tertiary-fixed": "#351300",
          "surface-bright": "#f7fbfd",
          "surface-dim": "#d7e1e6",
          "on-surface-variant": "#424750",
          "primary-fixed-dim": "#9be1f2",
          "surface-container-lowest": "#ffffff",
          "surface-variant": "#dde8ed",
          "outline-variant": "#c1ccd2",
          "tertiary-fixed": "#ffdfcc",
          "error-container": "#ffdad6",
          "secondary-container": "#ff7900",
          "primary": "#13a8d8",
          "on-primary-fixed-variant": "#006c9c",
          "on-secondary-container": "#301500",
          "on-primary-fixed": "#003346",
          "surface-container-highest": "#dde8ed",
          "tertiary": "#5a2100",
          "on-error": "#ffffff",
          "surface-container": "#e9f2f6",
          "on-surface": "#171c1f",
          "secondary-fixed": "#ffdcc4",
          "on-secondary-fixed": "#301400",
          "surface-container-low": "#f0f7fa",
          "tertiary-container": "#7f3500",
          "background": "#f7fbfd",
          "inverse-surface": "#26353b",
          "on-primary-container": "#e8faff",
          "on-tertiary": "#ffffff",
          "secondary-fixed-dim": "#ffb37d"
      },
      borderRadius: {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      fontFamily: {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
