/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
          "surface-container-high": "#e4e9ed",
          "surface-tint": "#2f5ea1",
          "on-tertiary-container": "#f79564",
          "on-primary": "#ffffff",
          "on-secondary-fixed-variant": "#723700",
          "tertiary-fixed-dim": "#ffb693",
          "surface": "#f6fafe",
          "inverse-primary": "#a9c7ff",
          "inverse-on-surface": "#edf1f5",
          "error": "#ba1a1a",
          "primary-fixed": "#d6e3ff",
          "outline": "#737781",
          "on-secondary": "#ffffff",
          "secondary": "#954a00",
          "on-background": "#171c1f",
          "on-tertiary-fixed-variant": "#783206",
          "on-error-container": "#93000a",
          "primary-container": "#004182",
          "on-tertiary-fixed": "#351000",
          "surface-bright": "#f6fafe",
          "surface-dim": "#d6dade",
          "on-surface-variant": "#424750",
          "primary-fixed-dim": "#a9c7ff",
          "surface-container-lowest": "#ffffff",
          "surface-variant": "#dfe3e7",
          "outline-variant": "#c3c6d2",
          "tertiary-fixed": "#ffdbcb",
          "error-container": "#ffdad6",
          "secondary-container": "#fd8100",
          "primary": "#002b5a",
          "on-primary-fixed-variant": "#0c4687",
          "on-secondary-container": "#5d2c00",
          "on-primary-fixed": "#001b3d",
          "surface-container-highest": "#dfe3e7",
          "tertiary": "#4e1c00",
          "on-error": "#ffffff",
          "surface-container": "#eaeef2",
          "on-surface": "#171c1f",
          "secondary-fixed": "#ffdcc6",
          "on-secondary-fixed": "#301400",
          "surface-container-low": "#f0f4f8",
          "tertiary-container": "#712d02",
          "background": "#f6fafe",
          "inverse-surface": "#2c3134",
          "on-primary-container": "#84aff7",
          "on-tertiary": "#ffffff",
          "secondary-fixed-dim": "#ffb785"
      },
      borderRadius: {
          "DEFAULT": "1rem",
          "lg": "2rem",
          "xl": "3rem",
          "full": "9999px"
      },
      fontFamily: {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
